[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = false

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "permit2/=lib/permit2/src/",
    "forge-std/=lib/forge-std/src/",
]

fs_permissions = [
    { access = "read", path = "lib/permit2/out" },
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 64

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1024, depth = 128 }
